version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: node
    environment:
      - cluster.name=cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.watcher.enabled=true
      - http.port=9200
      - network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=elastic
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    hostname: kibana
    environment:
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=["http://node:9200"]
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge